### ISSUE TITLE
Rebuild the websocket abstraction for use with new Router.kt

### ISSUE THREAD

**Issue by danneu** [danneu/kog#8]
I built the websocket abstraction for use with the old/original Router.kt. I need to rebuild/rethink it now that I have the new Router.kt (formerly SafeRouter.kt).

For one, the websocket acceptor should be refactored from its lambda-heavy impl to something with an ad-hoc usage more like:

```kotlin
websocket("/foo", fun(): = object : WebsocketHandler {
    override fun onConnect() = ...
    ...
})
```

Also, the websocket/jetty interop in Server.kt is nasty. But I really like the idea of nesting websocket handlers beneath existing middleware.

**Comment by ThraaxSession** [comment]
Oh oh. This will be a totally API break. I guess you will remove the current implementation?

**Comment by danneu** [comment]
@GinoHereIam This is a stale issue so I'll close it. 😄 

I don't see myself changing the websocket system anytime soon since I don't use it in production.

**Comment by danneu** [comment]
Oh, I've changed the websocket system since I made this issue 8 months ago. I just never updated the issue.

When I made this issue, the WebSocketHandler was a lot different than it is now.

**Comment by ThraaxSession** [comment]
@danneu I am glad now :D I want to use your websocket in "production" 

BTW great work! :) I am happy with it!
